/*
Copyright 2008-2010 Gephi
Authors : Mathieu Bastian <mathieu.bastian@gephi.org>
Website : http://www.gephi.org

This file is part of Gephi.

Gephi is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.
*/
package org.gephi.toolkit.demos;

import java.io.File;

/**
 * Provides a single location for files generated by the demos.
 */
final class DemoOutput {

    private static final File DIRECTORY = new File("target", "demo-output");

    private DemoOutput() {
    }

    static File directory() {
        if (!DIRECTORY.isDirectory() && !DIRECTORY.mkdirs()) {
            throw new IllegalStateException("Unable to create demo output directory: "
                + DIRECTORY.getAbsolutePath());
        }
        return DIRECTORY;
    }

    static File file(String name) {
        return new File(directory(), name);
    }
}
